name = "blinksite"
pages_build_output_dir = "./public"
compatibility_date = "2024-02-05"

[[d1_databases]]
binding = "DB" # PENTING: Nama binding harus "DB" agar cocok dengan kode (c.env.DB)
database_name = "bengkel"
database_id = "e73d5d93-b536-4efa-9dde-0dad225ddce5"

[[kv_namespaces]]
binding = "WIDGET_CACHE"
id = "93dda7d841544120bcb6c0926bdc87ca"

[[analytics_engine_datasets]]
binding = "ANALYTICS_ENGINE"
dataset = "serverless_events"
